#!/usr/bin/env bash
# Installs nginx server
# Installs and configures nginx, changes the listening port to 80

# sudo apt install nginx -y 
# sudo echo "Hello World!" | sudo tee -a /var/www/html/index.nginx-debian.html


apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx restart
