#!/usr/bin/env bash
# A init script that manages "manage_my_process"

case $1 in
    "start")
        ./manage_my_process &
	sudo sh -c 'echo $$ > /var/run/my_process.pid'
	echo "manage_my_process started"
    ;;
    "stop")
        pkill -SIGTERM -f "./manage_my_process"
	sudo rm /var/run/my_process.pid
	echo "manage_my_process stopped"
    ;;
    "restart")
        pkill -SIGTERM -f "./manage_my_process"
	if [ -e /var/run/my_process.pid ];
	then
	    sudo rm /var/run/my_process.pid
	fi
        ./manage_my_process &
	sudo sh -c 'echo $$ > /var/run/my_process.pid'
	echo "manage_my_process restarted"
    ;;
    *)
	echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
