#!/usr/bin/env bash
# A script that displays the contents of '/etc/passwd'
# Only the username, user 1d, and user home directory path is displayed

file="/etc/passwd"

while IFS=: read -r username _ userid _ _ homedir _
do    
    echo "$username:$userid:$homedir"
done < $file
