#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
# 4th it will display "bad luck from China" in place of
# 9th it will display "bad luck from Japan" in place of
# 17th it will display "bad luck from Italy" in place of
counter=1
while [ $counter -le 20 ]
do
    echo "$counter"
    case $counter in
        4)
            echo "bad luck from China"
        ;;
        9)
            echo "bad luck from Japan"
        ;;
        17)
            echo "bad luck from Italy"
        ;;
    esac
    (( counter++ ))
done
